uploading map to new relic
executing upload_map_file_to_new_relic
New Relic: map file upload attempt #1 (of 3)
Using URL: https://mobile-symbol-upload.newrelic.com
New Relic: Successfully uploaded map files
/Users/cborton/GitHub/synzi2/mobile/ios/app/NewRelicAgent.framework/Versions/A/Resources/generateMap.py", line 96, in <module>
    os.mkdir(workDir)
OSError: [Errno 17] File exists: '/Users/cborton/Library/Developer/Xcode/DerivedData/jitsi-meet-cmygzmklvtwyffcnhftmatfqqovk/Build/Intermediates.noindex/ArchiveIntermediates/jitsi-meet/IntermediateBuildFilesPath/app.build/Release-iphoneos/jitsi-meet.build/tmp'
New Relic: map file upload attempt #2 (of 3)
Using URL: https://mobile-symbol-upload.newrelic.com
Traceback (most recent call last):
  File "/Users/cborton/GitHub/synzi2/mobile/ios/app/NewRelicAgent.framework/Versions/A/Resources/generateMap.py", line 96, in <module>
    os.mkdir(workDir)
OSError: [Errno 17] File exists: '/Users/cborton/Library/Developer/Xcode/DerivedData/jitsi-meet-cmygzmklvtwyffcnhftmatfqqovk/Build/Intermediates.noindex/ArchiveIntermediates/jitsi-meet/IntermediateBuildFilesPath/app.build/Release-iphoneos/jitsi-meet.build/tmp'
New Relic: map file upload attempt #3 (of 3)
Using URL: https://mobile-symbol-upload.newrelic.com
Traceback (most recent call last):
  File "/Users/cborton/GitHub/synzi2/mobile/ios/app/NewRelicAgent.framework/Versions/A/Resources/generateMap.py", line 96, in <module>
    os.mkdir(workDir)
OSError: [Errno 17] File exists: '/Users/cborton/Library/Developer/Xcode/DerivedData/jitsi-meet-cmygzmklvtwyffcnhftmatfqqovk/Build/Intermediates.noindex/ArchiveIntermediates/jitsi-meet/IntermediateBuildFilesPath/app.build/Release-iphoneos/jitsi-meet.build/tmp'
executing upload_dsym_to_new_relic
new relic: successfully uploaded dsym files
